import type { AgentsListResult, SkillStatusEntry, SkillStatusReport } from "../../api/types.ts";
import { renderSkills } from "./view.ts";

type SkillsProps = Parameters<typeof renderSkills>[0];

export function normalizeText(node: Element | DocumentFragment): string {
  return node.textContent?.replace(/\s+/g, " ").trim() ?? "";
}

export function createSkill(overrides: Partial<SkillStatusEntry> = {}): SkillStatusEntry {
  return {
    name: "Repo Skill",
    description: "",
    source: "workspace",
    filePath: "/tmp/skill",
    baseDir: "/tmp",
    skillKey: "repo-skill",
    bundled: false,
    primaryEnv: "OPENAI_API_KEY",
    emoji: undefined,
    homepage: "https://example.com",
    always: false,
    disabled: false,
    blockedByAllowlist: false,
    blockedByAgentFilter: false,
    eligible: true,
    requirements: { anyBins: [], bins: [], env: [], config: [], os: [] },
    missing: { anyBins: [], bins: [], env: [], config: [], os: [] },
    configChecks: [],
    install: [],
    ...overrides,
  };
}

export function createProps(overrides: Partial<SkillsProps> = {}): SkillsProps {
  const report: SkillStatusReport = {
    workspaceDir: "/tmp/workspace",
    managedSkillsDir: "/tmp/skills",
    skills: [createSkill()],
  };
  const agentsList: AgentsListResult = {
    defaultId: "main",
    mainKey: "main",
    scope: "project",
    agents: [
      { id: "main", name: "Main" },
      { id: "research", identity: { name: "Research", avatar: "R" } },
    ],
  };
  return {
    canUpdate: true,
    canInstall: true,
    connected: true,
    loading: false,
    report,
    agentsList,
    selectedAgentId: "main",
    error: null,
    filter: "",
    statusFilter: "all",
    edits: {},
    operation: null,
    messages: {},
    detailKey: null,
    detailTab: "overview",
    clawhubVerdicts: {},
    clawhubVerdictsLoading: false,
    clawhubVerdictsError: null,
    skillCardContents: {},
    skillCardLoadingKey: null,
    skillCardErrors: {},
    clawhubQuery: "",
    clawhubResults: null,
    clawhubSearchLoading: false,
    clawhubSearchError: null,
    clawhubDetail: null,
    clawhubDetailSlug: null,
    clawhubDetailLoading: false,
    clawhubDetailError: null,
    clawhubInstallMessage: null,
    skillHubConfig: null,
    skillHubConfigLoading: false,
    skillHubQuery: "",
    skillHubResults: null,
    skillHubSearchLoading: false,
    skillHubError: null,
    skillHubDetailRef: null,
    skillHubDetail: null,
    skillHubDetailLoading: false,
    skillHubSelectedVersion: "",
    skillHubPublishSkill: null,
    skillHubPublishNamespace: "",
    skillHubPublishVersion: "0.1.0",
    skillHubPublishVisibility: "PUBLIC",
    skillHubOperation: null,
    skillHubMessage: null,
    onAgentChange: () => undefined,
    onFilterChange: () => undefined,
    onStatusFilterChange: () => undefined,
    onRefresh: () => undefined,
    onToggle: () => undefined,
    onEdit: () => undefined,
    onSaveKey: () => undefined,
    onInstall: () => undefined,
    onDetailOpen: () => undefined,
    onDetailClose: () => undefined,
    onDetailTabChange: () => undefined,
    onClawHubQueryChange: () => undefined,
    onClawHubDetailOpen: () => undefined,
    onClawHubDetailClose: () => undefined,
    onClawHubInstall: () => undefined,
    onSkillHubQueryChange: () => undefined,
    onSkillHubSearch: () => undefined,
    onSkillHubDetailOpen: () => undefined,
    onSkillHubDetailClose: () => undefined,
    onSkillHubVersionChange: () => undefined,
    onSkillHubInstall: () => undefined,
    onSkillHubPublishOpen: () => undefined,
    onSkillHubPublishClose: () => undefined,
    onSkillHubPublishNamespaceChange: () => undefined,
    onSkillHubPublishVersionChange: () => undefined,
    onSkillHubPublishVisibilityChange: () => undefined,
    onSkillHubPublish: () => undefined,
    ...overrides,
  };
}
