export const PLATFORMCLAW_WEB_GATEWAY_METHODS = [
  "agent.identity.get",
  "agents.files.get",
  "agents.files.list",
  "agents.files.set",
  "agents.list",
  "chat.abort",
  "chat.history",
  "chat.message.get",
  "chat.metadata",
  "chat.send",
  "chat.startup",
  "chat.toolTitles",
  "commands.list",
  "cron.add",
  "cron.get",
  "cron.list",
  "cron.remove",
  "cron.run",
  "cron.runs",
  "cron.status",
  "cron.update",
  "models.list",
  "plugins.install",
  "plugins.list",
  "plugins.search",
  "plugins.setEnabled",
  "plugins.uninstall",
  "sessions.abort",
  "sessions.create",
  "sessions.delete",
  "sessions.describe",
  "sessions.list",
  "sessions.messages.subscribe",
  "sessions.messages.unsubscribe",
  "sessions.observer.ask",
  "sessions.observer.visibility",
  "sessions.patch",
  "sessions.preview",
  "sessions.resolve",
  "sessions.search",
  "sessions.usage",
  "skills.detail",
  "skills.install",
  "skills.proposals.apply",
  "skills.proposals.evaluate",
  "skills.proposals.historyScan",
  "skills.proposals.historyStatus",
  "skills.proposals.inspect",
  "skills.proposals.list",
  "skills.proposals.reject",
  "skills.proposals.requestRevision",
  "skills.search",
  "skills.securityVerdicts",
  "skills.skillCard",
  "skills.status",
  "tasks.cancel",
  "tasks.get",
  "tasks.list",
  "tools.catalog",
  "tools.effective",
  "usage.cost",
  "users.self",
] as const;

export type PlatformClawWebGatewayMethod = (typeof PLATFORMCLAW_WEB_GATEWAY_METHODS)[number];

export const PLATFORMCLAW_WEB_ALLOWED_METHODS = new Set<string>(PLATFORMCLAW_WEB_GATEWAY_METHODS);
export const PLATFORMCLAW_WEB_ALLOWED_PARAMS = new Map<string, ReadonlySet<string>>([
  ["agent.identity.get", new Set(["agentId", "sessionKey"])],
  ["agents.files.get", new Set(["agentId", "name"])],
  ["agents.files.list", new Set(["agentId"])],
  ["agents.files.set", new Set(["agentId", "name", "content"])],
  ["agents.list", new Set()],
  ["chat.abort", new Set(["sessionKey", "agentId", "preserveSideRuns", "runId"])],
  [
    "chat.history",
    new Set(["sessionKey", "agentId", "limit", "offset", "messageId", "sessionId", "maxChars"]),
  ],
  ["chat.message.get", new Set(["sessionKey", "agentId", "messageId", "maxChars"])],
  ["chat.metadata", new Set(["agentId"])],
  [
    "chat.send",
    new Set([
      "sessionKey",
      "agentId",
      "sessionId",
      "message",
      "thinking",
      "fastMode",
      "fastAutoOnSeconds",
      "queueMode",
      "deliver",
      "attachments",
      "timeoutMs",
      "idempotencyKey",
      "expectedLeafEntryId",
      "replyToId",
      "__controlUiReconnectResume",
    ]),
  ],
  [
    "chat.startup",
    new Set(["sessionKey", "agentId", "limit", "offset", "messageId", "sessionId", "maxChars"]),
  ],
  ["chat.toolTitles", new Set(["sessionKey", "agentId", "items"])],
  ["commands.list", new Set(["agentId", "includeArgs", "scope"])],
  [
    "cron.add",
    new Set([
      "agentId",
      "deleteAfterRun",
      "delivery",
      "description",
      "enabled",
      "failureAlert",
      "name",
      "payload",
      "schedule",
      "sessionKey",
      "sessionTarget",
      "wakeMode",
    ]),
  ],
  ["cron.get", new Set(["id", "jobId"])],
  [
    "cron.list",
    new Set([
      "agentId",
      "enabled",
      "includeDisabled",
      "includeDeliveryPreviews",
      "lastRunStatus",
      "limit",
      "offset",
      "query",
      "scheduleKind",
      "sortBy",
      "sortDir",
    ]),
  ],
  ["cron.remove", new Set(["expectedConfigRevision", "id", "jobId"])],
  ["cron.run", new Set(["expectedConfigRevision", "id", "jobId", "mode"])],
  [
    "cron.runs",
    new Set([
      "agentId",
      "deliveryStatus",
      "deliveryStatuses",
      "id",
      "jobId",
      "limit",
      "offset",
      "query",
      "runId",
      "scope",
      "sortDir",
      "status",
      "statuses",
    ]),
  ],
  ["cron.status", new Set()],
  ["cron.update", new Set(["expectedConfigRevision", "id", "jobId", "patch"])],
  ["models.list", new Set(["view"])],
  [
    "plugins.install",
    new Set(["source", "packageName", "version", "acknowledgeClawHubRisk", "pluginId"]),
  ],
  ["plugins.list", new Set()],
  ["plugins.search", new Set(["query", "limit"])],
  ["plugins.setEnabled", new Set(["pluginId", "enabled"])],
  ["plugins.uninstall", new Set(["pluginId"])],
  ["sessions.abort", new Set(["key", "agentId", "clearQueued"])],
  [
    "sessions.create",
    new Set([
      "key",
      "agentId",
      "label",
      "thinkingLevel",
      "catalogId",
      "parentSessionKey",
      "fork",
      "emitCommandHooks",
      "succeedsParent",
      "message",
      "attachments",
    ]),
  ],
  ["sessions.delete", new Set(["key", "agentId", "deleteTranscript", "archivedOnly"])],
  ["sessions.describe", new Set(["key", "includeDerivedTitles", "includeLastMessage"])],
  [
    "sessions.list",
    new Set([
      "limit",
      "offset",
      "activeMinutes",
      "requireLastInteraction",
      "sortBy",
      "includeGlobal",
      "includeUnknown",
      "configuredAgentsOnly",
      "includeDerivedTitles",
      "includeLastMessage",
      "label",
      "spawnedBy",
      "agentId",
      "search",
      "archived",
    ]),
  ],
  ["sessions.messages.subscribe", new Set(["key", "agentId"])],
  ["sessions.messages.unsubscribe", new Set(["key", "agentId"])],
  ["sessions.observer.ask", new Set(["sessionKey", "question"])],
  ["sessions.observer.visibility", new Set(["visible"])],
  [
    "sessions.patch",
    new Set([
      "key",
      "agentId",
      "label",
      "category",
      "icon",
      "archived",
      "pinned",
      "unread",
      "thinkingLevel",
      "fastMode",
      "verboseLevel",
      "traceLevel",
      "reasoningLevel",
      "responseUsage",
      "model",
    ]),
  ],
  ["sessions.preview", new Set(["keys", "limit", "maxChars"])],
  [
    "sessions.resolve",
    new Set([
      "key",
      "sessionId",
      "label",
      "agentId",
      "spawnedBy",
      "includeGlobal",
      "includeUnknown",
      "allowMissing",
    ]),
  ],
  ["sessions.search", new Set(["agentId", "sessionKeys", "query", "limit"])],
  [
    "sessions.usage",
    new Set([
      "key",
      "agentId",
      "agentScope",
      "startDate",
      "endDate",
      "mode",
      "range",
      "groupBy",
      "includeHistorical",
      "utcOffset",
      "timeZone",
      "limit",
      "includeContextWeight",
    ]),
  ],
  ["skills.detail", new Set(["slug"])],
  [
    "skills.install",
    new Set([
      "agentId",
      "source",
      "slug",
      "version",
      "force",
      "acknowledgeClawHubRisk",
      "timeoutMs",
    ]),
  ],
  [
    "skills.proposals.apply",
    new Set(["agentId", "proposalId", "expectedRevisionHash", "correlationId", "reason"]),
  ],
  [
    "skills.proposals.evaluate",
    new Set(["agentId", "proposalId", "expectedRevisionHash", "correlationId"]),
  ],
  ["skills.proposals.historyScan", new Set(["agentId", "direction"])],
  ["skills.proposals.historyStatus", new Set(["agentId"])],
  ["skills.proposals.inspect", new Set(["agentId", "proposalId"])],
  ["skills.proposals.list", new Set(["agentId"])],
  [
    "skills.proposals.reject",
    new Set(["agentId", "proposalId", "expectedRevisionHash", "correlationId", "reason"]),
  ],
  [
    "skills.proposals.requestRevision",
    new Set([
      "agentId",
      "targetAgentId",
      "proposalId",
      "instructions",
      "sessionKey",
      "sessionId",
      "idempotencyKey",
    ]),
  ],
  ["skills.search", new Set(["query", "limit"])],
  ["skills.securityVerdicts", new Set(["agentId"])],
  ["skills.skillCard", new Set(["agentId", "skillKey"])],
  ["skills.status", new Set(["agentId", "refresh"])],
  ["tasks.cancel", new Set(["taskId", "reason"])],
  ["tasks.get", new Set(["taskId"])],
  ["tasks.list", new Set(["status", "agentId", "sessionKey", "limit", "cursor"])],
  ["tools.catalog", new Set(["agentId", "includePlugins"])],
  ["tools.effective", new Set(["agentId", "sessionKey"])],
  [
    "usage.cost",
    new Set([
      "agentId",
      "agentScope",
      "startDate",
      "endDate",
      "days",
      "range",
      "mode",
      "utcOffset",
      "timeZone",
    ]),
  ],
  ["users.self", new Set()],
]);

export const PLATFORMCLAW_WEB_AGENT_ONLY_METHODS = new Set([
  "agent.identity.get",
  "agents.files.get",
  "agents.files.list",
  "agents.files.set",
  "chat.metadata",
  "commands.list",
  "sessions.usage",
  "skills.install",
  "skills.proposals.apply",
  "skills.proposals.evaluate",
  "skills.proposals.historyScan",
  "skills.proposals.historyStatus",
  "skills.proposals.inspect",
  "skills.proposals.list",
  "skills.proposals.reject",
  "skills.proposals.requestRevision",
  "skills.securityVerdicts",
  "skills.skillCard",
  "skills.status",
  "tasks.list",
  "tools.catalog",
  "usage.cost",
]);

export const PLATFORMCLAW_WEB_ADMIN_METHODS = new Set<string>([
  "plugins.install",
  "plugins.list",
  "plugins.search",
  "plugins.setEnabled",
  "plugins.uninstall",
]);

export const PLATFORMCLAW_WEB_SESSION_KEY_METHODS = new Map<string, string>([
  ["chat.abort", "sessionKey"],
  ["chat.history", "sessionKey"],
  ["chat.message.get", "sessionKey"],
  ["chat.send", "sessionKey"],
  ["chat.startup", "sessionKey"],
  ["chat.toolTitles", "sessionKey"],
  ["sessions.abort", "key"],
  ["sessions.describe", "key"],
  ["sessions.messages.subscribe", "key"],
  ["sessions.messages.unsubscribe", "key"],
  ["sessions.patch", "key"],
  ["tools.effective", "sessionKey"],
]);
