export const PLATFORMCLAW_WEB_GATEWAY_METHODS = [
  "agent.identity.get",
  "agents.files.get",
  "agents.files.list",
  "agents.files.set",
  "agents.list",
  "chat.abort",
  "chat.history",
  "chat.message.get",
  "chat.metadata",
  "chat.send",
  "chat.startup",
  "chat.toolTitles",
  "commands.list",
  "models.list",
  "sessions.abort",
  "sessions.create",
  "sessions.describe",
  "sessions.list",
  "sessions.messages.subscribe",
  "sessions.messages.unsubscribe",
  "sessions.patch",
  "sessions.preview",
  "sessions.resolve",
  "sessions.search",
  "skills.status",
  "tools.catalog",
  "tools.effective",
] as const;

export type PlatformClawWebGatewayMethod = (typeof PLATFORMCLAW_WEB_GATEWAY_METHODS)[number];

export const PLATFORMCLAW_WEB_ALLOWED_METHODS = new Set<string>(PLATFORMCLAW_WEB_GATEWAY_METHODS);
export const PLATFORMCLAW_WEB_ALLOWED_PARAMS = new Map<string, ReadonlySet<string>>([
  ["agent.identity.get", new Set(["agentId", "sessionKey"])],
  ["agents.files.get", new Set(["agentId", "name"])],
  ["agents.files.list", new Set(["agentId"])],
  ["agents.files.set", new Set(["agentId", "name", "content"])],
  ["agents.list", new Set()],
  ["chat.abort", new Set(["sessionKey", "agentId", "preserveSideRuns", "runId"])],
  [
    "chat.history",
    new Set(["sessionKey", "agentId", "limit", "offset", "messageId", "sessionId", "maxChars"]),
  ],
  ["chat.message.get", new Set(["sessionKey", "agentId", "messageId", "maxChars"])],
  ["chat.metadata", new Set(["agentId"])],
  [
    "chat.send",
    new Set([
      "sessionKey",
      "agentId",
      "sessionId",
      "message",
      "thinking",
      "fastMode",
      "fastAutoOnSeconds",
      "queueMode",
      "deliver",
      "attachments",
      "timeoutMs",
      "idempotencyKey",
      "__controlUiReconnectResume",
    ]),
  ],
  [
    "chat.startup",
    new Set(["sessionKey", "agentId", "limit", "offset", "messageId", "sessionId", "maxChars"]),
  ],
  ["chat.toolTitles", new Set(["sessionKey", "agentId", "items"])],
  ["commands.list", new Set(["agentId", "includeArgs", "scope"])],
  ["models.list", new Set(["view"])],
  ["sessions.abort", new Set(["key", "agentId"])],
  [
    "sessions.create",
    new Set([
      "key",
      "agentId",
      "label",
      "thinkingLevel",
      "catalogId",
      "parentSessionKey",
      "fork",
      "emitCommandHooks",
      "succeedsParent",
      "message",
    ]),
  ],
  ["sessions.describe", new Set(["key", "includeDerivedTitles", "includeLastMessage"])],
  [
    "sessions.list",
    new Set([
      "limit",
      "offset",
      "activeMinutes",
      "requireLastInteraction",
      "sortBy",
      "includeGlobal",
      "includeUnknown",
      "configuredAgentsOnly",
      "includeDerivedTitles",
      "includeLastMessage",
      "label",
      "spawnedBy",
      "agentId",
      "search",
      "archived",
    ]),
  ],
  ["sessions.messages.subscribe", new Set(["key", "agentId"])],
  ["sessions.messages.unsubscribe", new Set(["key", "agentId"])],
  [
    "sessions.patch",
    new Set([
      "key",
      "agentId",
      "label",
      "category",
      "pinned",
      "unread",
      "thinkingLevel",
      "fastMode",
      "verboseLevel",
      "traceLevel",
      "reasoningLevel",
      "responseUsage",
      "model",
    ]),
  ],
  ["sessions.preview", new Set(["keys", "limit", "maxChars"])],
  [
    "sessions.resolve",
    new Set([
      "key",
      "sessionId",
      "label",
      "agentId",
      "spawnedBy",
      "includeGlobal",
      "includeUnknown",
      "allowMissing",
    ]),
  ],
  ["sessions.search", new Set(["agentId", "sessionKeys", "query", "limit"])],
  ["skills.status", new Set(["agentId"])],
  ["tools.catalog", new Set(["agentId", "includePlugins"])],
  ["tools.effective", new Set(["agentId", "sessionKey"])],
]);

export const PLATFORMCLAW_WEB_AGENT_ONLY_METHODS = new Set([
  "agent.identity.get",
  "agents.files.get",
  "agents.files.list",
  "agents.files.set",
  "chat.metadata",
  "commands.list",
  "skills.status",
  "tools.catalog",
]);

export const PLATFORMCLAW_WEB_SESSION_KEY_METHODS = new Map<string, string>([
  ["chat.abort", "sessionKey"],
  ["chat.history", "sessionKey"],
  ["chat.message.get", "sessionKey"],
  ["chat.send", "sessionKey"],
  ["chat.startup", "sessionKey"],
  ["chat.toolTitles", "sessionKey"],
  ["sessions.abort", "key"],
  ["sessions.describe", "key"],
  ["sessions.messages.subscribe", "key"],
  ["sessions.messages.unsubscribe", "key"],
  ["sessions.patch", "key"],
  ["tools.effective", "sessionKey"],
]);
