export const PLATFORMCLAW_WEB_GATEWAY_METHODS = [
  "agent.identity.get",
  "agents.files.get",
  "agents.files.list",
  "agents.files.set",
  "agents.list",
  "agents.workspace.get",
  "artifacts.download",
  "artifacts.list",
  "chat.abort",
  "chat.history",
  "chat.message.get",
  "chat.metadata",
  "chat.send",
  "chat.startup",
  "chat.toolTitles",
  "commands.list",
  "controlUi.sessionPullRequests.subscribe",
  "cron.add",
  "cron.get",
  "cron.list",
  "cron.remove",
  "cron.run",
  "cron.runs",
  "cron.status",
  "cron.update",
  "doctor.memory.backfillDreamDiary",
  "doctor.memory.dedupeDreamDiary",
  "doctor.memory.dreamDiary",
  "doctor.memory.repairDreamingArtifacts",
  "doctor.memory.resetDreamDiary",
  "doctor.memory.resetGroundedShortTerm",
  "doctor.memory.status",
  "models.list",
  "memory.search",
  "approval.history",
  "approval.get",
  "approval.resolve",
  "plugins.install",
  "plugins.list",
  "plugins.search",
  "plugins.setEnabled",
  "plugins.uninstall",
  "plugin.surface.refresh",
  "platformclaw.memory.claim.purge",
  "platformclaw.memory.claim.retire",
  "platformclaw.memory.lifecycle",
  "platformclaw.memory.get",
  "platformclaw.memory.promotion.decide",
  "platformclaw.memory.promotion.publishDirect",
  "platformclaw.memory.promotion.submit",
  "question.get",
  "question.list",
  "question.resolve",
  "sessions.abort",
  "sessions.compact",
  "sessions.companion.ask",
  "sessions.companion.reset",
  "sessions.companion.state",
  "sessions.create",
  "sessions.delete",
  "sessions.describe",
  "sessions.files.get",
  "sessions.files.list",
  "sessions.fork",
  "sessions.list",
  "sessions.messages.subscribe",
  "sessions.messages.unsubscribe",
  "sessions.observer.visibility",
  "sessions.patch",
  "sessions.preview",
  "sessions.rewind",
  "sessions.reset",
  "sessions.resolve",
  "sessions.search",
  "sessions.steer",
  "sessions.subscribe",
  "sessions.usage",
  "skills.detail",
  "skills.install",
  "skills.proposals.apply",
  "skills.proposals.evaluate",
  "skills.proposals.historyScan",
  "skills.proposals.historyStatus",
  "skills.proposals.inspect",
  "skills.proposals.list",
  "skills.proposals.reject",
  "skills.proposals.requestRevision",
  "skills.search",
  "skills.securityVerdicts",
  "skills.skillCard",
  "skills.status",
  "tasks.cancel",
  "tasks.dismiss",
  "tasks.get",
  "tasks.list",
  "tasks.retry",
  "terminal.attach",
  "terminal.close",
  "terminal.input",
  "terminal.list",
  "terminal.open",
  "terminal.resize",
  "taskSuggestions.accept",
  "taskSuggestions.dismiss",
  "taskSuggestions.list",
  "tools.catalog",
  "tools.effective",
  "usage.cost",
  "users.self",
  "wiki.get",
  "wiki.importInsights",
  "wiki.overview",
  "wiki.search",
  "wiki.status",
] as const;

export type PlatformClawWebGatewayMethod = (typeof PLATFORMCLAW_WEB_GATEWAY_METHODS)[number];

export const PLATFORMCLAW_WEB_ALLOWED_METHODS = new Set<string>(PLATFORMCLAW_WEB_GATEWAY_METHODS);
export const PLATFORMCLAW_WEB_LOCAL_METHODS = new Set<string>([
  "commands.list",
  "platformclaw.memory.claim.purge",
  "platformclaw.memory.claim.retire",
  "platformclaw.memory.lifecycle",
  "platformclaw.memory.get",
  "platformclaw.memory.promotion.decide",
  "platformclaw.memory.promotion.publishDirect",
  "platformclaw.memory.promotion.submit",
]);
export const PLATFORMCLAW_WEB_ALLOWED_PARAMS = new Map<string, ReadonlySet<string>>([
  ["agent.identity.get", new Set(["agentId", "sessionKey"])],
  ["agents.files.get", new Set(["agentId", "name"])],
  ["agents.files.list", new Set(["agentId"])],
  ["agents.files.set", new Set(["agentId", "name", "content"])],
  ["agents.list", new Set()],
  ["agents.workspace.get", new Set(["agentId", "path"])],
  ["artifacts.download", new Set(["sessionKey", "artifactId", "agentId"])],
  ["artifacts.list", new Set(["sessionKey", "agentId"])],
  ["chat.abort", new Set(["sessionKey", "agentId", "preserveSideRuns", "runId"])],
  [
    "chat.history",
    new Set(["sessionKey", "agentId", "limit", "offset", "messageId", "sessionId", "maxChars"]),
  ],
  ["chat.message.get", new Set(["sessionKey", "agentId", "messageId", "maxChars"])],
  ["chat.metadata", new Set(["agentId"])],
  [
    "chat.send",
    new Set([
      "sessionKey",
      "agentId",
      "sessionId",
      "message",
      "thinking",
      "fastMode",
      "fastAutoOnSeconds",
      "queueMode",
      "deliver",
      "attachments",
      "timeoutMs",
      "idempotencyKey",
      "expectedLeafEntryId",
      "replyToId",
      "__controlUiReconnectResume",
    ]),
  ],
  [
    "chat.startup",
    new Set(["sessionKey", "agentId", "limit", "offset", "messageId", "sessionId", "maxChars"]),
  ],
  ["chat.toolTitles", new Set(["sessionKey", "agentId", "items"])],
  ["commands.list", new Set(["agentId", "includeArgs", "scope"])],
  ["controlUi.sessionPullRequests.subscribe", new Set(["sessionKeys", "refreshSessionKeys"])],
  [
    "cron.add",
    new Set([
      "agentId",
      "deleteAfterRun",
      "delivery",
      "description",
      "enabled",
      "failureAlert",
      "name",
      "payload",
      "schedule",
      "sessionKey",
      "sessionTarget",
      "wakeMode",
    ]),
  ],
  ["cron.get", new Set(["id", "jobId"])],
  [
    "cron.list",
    new Set([
      "agentId",
      "enabled",
      "includeDisabled",
      "includeDeliveryPreviews",
      "lastRunStatus",
      "limit",
      "offset",
      "query",
      "scheduleKind",
      "sortBy",
      "sortDir",
    ]),
  ],
  ["cron.remove", new Set(["expectedConfigRevision", "id", "jobId"])],
  [
    "cron.run",
    new Set(["expectedConfigRevision", "expectedProcessInstanceId", "id", "jobId", "mode"]),
  ],
  [
    "cron.runs",
    new Set([
      "agentId",
      "deliveryStatus",
      "deliveryStatuses",
      "id",
      "jobId",
      "limit",
      "offset",
      "query",
      "runId",
      "scope",
      "sortDir",
      "status",
      "statuses",
    ]),
  ],
  ["cron.status", new Set()],
  ["cron.update", new Set(["expectedConfigRevision", "id", "jobId", "patch"])],
  ["doctor.memory.backfillDreamDiary", new Set(["agentId"])],
  ["doctor.memory.dedupeDreamDiary", new Set(["agentId"])],
  ["doctor.memory.dreamDiary", new Set(["agentId"])],
  ["doctor.memory.repairDreamingArtifacts", new Set(["agentId"])],
  ["doctor.memory.resetDreamDiary", new Set(["agentId"])],
  ["doctor.memory.resetGroundedShortTerm", new Set(["agentId"])],
  ["doctor.memory.status", new Set(["agentId", "probe"])],
  ["models.list", new Set(["view"])],
  ["memory.search", new Set(["agentId", "query"])],
  ["approval.history", new Set(["agentId", "cursor", "kind", "limit"])],
  ["approval.get", new Set(["id"])],
  ["approval.resolve", new Set(["id", "kind", "decision"])],
  [
    "plugins.install",
    new Set(["source", "packageName", "version", "acknowledgeClawHubRisk", "pluginId"]),
  ],
  ["plugins.list", new Set()],
  ["plugins.search", new Set(["query", "limit"])],
  ["plugins.setEnabled", new Set(["pluginId", "enabled"])],
  ["plugins.uninstall", new Set(["pluginId"])],
  ["plugin.surface.refresh", new Set(["surface", "observedUrl"])],
  ["platformclaw.memory.claim.purge", new Set(["claimId", "reason"])],
  ["platformclaw.memory.claim.retire", new Set(["claimId", "reason"])],
  ["platformclaw.memory.lifecycle", new Set(["claims", "submitted", "reviewable"])],
  ["platformclaw.memory.get", new Set(["agentId", "path", "fromLine", "lineCount"])],
  ["platformclaw.memory.promotion.decide", new Set(["requestId", "decision", "reason"])],
  [
    "platformclaw.memory.promotion.publishDirect",
    new Set([
      "sourceKind",
      "sourceClaimId",
      "expectedSourceRevision",
      "targetKind",
      "targetScopeId",
      "proposedText",
      "evidence",
      "reason",
    ]),
  ],
  [
    "platformclaw.memory.promotion.submit",
    new Set([
      "sourceKind",
      "sourceClaimId",
      "expectedSourceRevision",
      "targetKind",
      "targetScopeId",
      "proposedText",
      "evidence",
      "reason",
    ]),
  ],
  ["question.get", new Set(["id"])],
  ["question.list", new Set()],
  ["question.resolve", new Set(["id", "answers", "cancel"])],
  ["sessions.abort", new Set(["key", "agentId", "clearQueued"])],
  ["sessions.compact", new Set(["key", "agentId"])],
  ["sessions.companion.ask", new Set(["sessionKey", "question"])],
  ["sessions.companion.reset", new Set(["sessionKey"])],
  ["sessions.companion.state", new Set(["sessionKey"])],
  [
    "sessions.create",
    new Set([
      "key",
      "agentId",
      "label",
      "thinkingLevel",
      "catalogId",
      "parentSessionKey",
      "fork",
      "emitCommandHooks",
      "succeedsParent",
      "message",
      "attachments",
    ]),
  ],
  ["sessions.delete", new Set(["key", "agentId", "deleteTranscript", "archivedOnly"])],
  ["sessions.describe", new Set(["key", "includeDerivedTitles", "includeLastMessage"])],
  ["sessions.files.get", new Set(["sessionKey", "path", "agentId"])],
  ["sessions.files.list", new Set(["sessionKey", "path", "search", "agentId"])],
  ["sessions.fork", new Set(["sessionKey", "entryId", "agentId"])],
  [
    "sessions.list",
    new Set([
      "limit",
      "offset",
      "activeMinutes",
      "requireLastInteraction",
      "sortBy",
      "includeGlobal",
      "includeUnknown",
      "configuredAgentsOnly",
      "includeDerivedTitles",
      "includeLastMessage",
      "label",
      "boardFace",
      "creatorId",
      "spawnedBy",
      "agentId",
      "search",
      "archived",
    ]),
  ],
  ["sessions.messages.subscribe", new Set(["key", "agentId", "includeApprovals"])],
  ["sessions.messages.unsubscribe", new Set(["key", "agentId"])],
  ["sessions.observer.visibility", new Set(["visible"])],
  [
    "sessions.patch",
    new Set([
      "key",
      "agentId",
      "label",
      "category",
      "boardFace",
      "icon",
      "archived",
      "pinned",
      "unread",
      "thinkingLevel",
      "fastMode",
      "verboseLevel",
      "traceLevel",
      "reasoningLevel",
      "responseUsage",
      "model",
    ]),
  ],
  ["sessions.preview", new Set(["keys", "limit", "maxChars"])],
  ["sessions.rewind", new Set(["sessionKey", "entryId", "agentId"])],
  ["sessions.reset", new Set(["key", "agentId", "reason"])],
  [
    "sessions.resolve",
    new Set([
      "key",
      "sessionId",
      "label",
      "agentId",
      "spawnedBy",
      "includeGlobal",
      "includeUnknown",
      "allowMissing",
    ]),
  ],
  ["sessions.search", new Set(["agentId", "sessionKeys", "query", "limit"])],
  ["sessions.steer", new Set(["key", "agentId", "message"])],
  ["sessions.subscribe", new Set()],
  [
    "sessions.usage",
    new Set([
      "key",
      "agentId",
      "agentScope",
      "startDate",
      "endDate",
      "mode",
      "range",
      "groupBy",
      "includeHistorical",
      "utcOffset",
      "timeZone",
      "limit",
      "includeContextWeight",
    ]),
  ],
  ["skills.detail", new Set(["slug"])],
  [
    "skills.install",
    new Set([
      "agentId",
      "source",
      "slug",
      "version",
      "force",
      "acknowledgeClawHubRisk",
      "timeoutMs",
    ]),
  ],
  [
    "skills.proposals.apply",
    new Set(["agentId", "proposalId", "expectedRevisionHash", "correlationId", "reason"]),
  ],
  [
    "skills.proposals.evaluate",
    new Set(["agentId", "proposalId", "expectedRevisionHash", "correlationId"]),
  ],
  ["skills.proposals.historyScan", new Set(["agentId", "direction"])],
  ["skills.proposals.historyStatus", new Set(["agentId"])],
  ["skills.proposals.inspect", new Set(["agentId", "proposalId"])],
  ["skills.proposals.list", new Set(["agentId"])],
  [
    "skills.proposals.reject",
    new Set(["agentId", "proposalId", "expectedRevisionHash", "correlationId", "reason"]),
  ],
  [
    "skills.proposals.requestRevision",
    new Set([
      "agentId",
      "targetAgentId",
      "proposalId",
      "instructions",
      "sessionKey",
      "sessionId",
      "idempotencyKey",
    ]),
  ],
  ["skills.search", new Set(["query", "limit"])],
  ["skills.securityVerdicts", new Set(["agentId"])],
  ["skills.skillCard", new Set(["agentId", "skillKey"])],
  ["skills.status", new Set(["agentId", "refresh"])],
  ["tasks.cancel", new Set(["taskId", "reason"])],
  ["tasks.dismiss", new Set(["taskIds"])],
  ["tasks.get", new Set(["taskId"])],
  ["tasks.list", new Set(["status", "agentId", "sessionKey", "limit", "cursor"])],
  ["tasks.retry", new Set(["taskIds"])],
  ["terminal.attach", new Set(["sessionId"])],
  ["terminal.close", new Set(["sessionId"])],
  ["terminal.input", new Set(["sessionId", "data"])],
  ["terminal.list", new Set()],
  ["terminal.open", new Set(["cols", "rows"])],
  ["terminal.resize", new Set(["sessionId", "cols", "rows"])],
  ["taskSuggestions.accept", new Set(["taskId"])],
  ["taskSuggestions.dismiss", new Set(["taskId", "reason"])],
  ["taskSuggestions.list", new Set(["agentId", "sessionKey"])],
  ["tools.catalog", new Set(["agentId", "includePlugins"])],
  ["tools.effective", new Set(["agentId", "sessionKey"])],
  [
    "usage.cost",
    new Set([
      "agentId",
      "agentScope",
      "startDate",
      "endDate",
      "days",
      "range",
      "mode",
      "utcOffset",
      "timeZone",
    ]),
  ],
  ["users.self", new Set()],
  ["wiki.get", new Set(["agentId", "lookup", "fromLine", "lineCount"])],
  ["wiki.importInsights", new Set(["agentId"])],
  ["wiki.overview", new Set(["agentId"])],
  ["wiki.search", new Set(["agentId", "query", "maxResults", "mode"])],
  ["wiki.status", new Set(["agentId"])],
]);

export const PLATFORMCLAW_WEB_AGENT_ONLY_METHODS = new Set([
  "agent.identity.get",
  "agents.files.get",
  "agents.files.list",
  "agents.files.set",
  "agents.workspace.get",
  "approval.history",
  "chat.metadata",
  "commands.list",
  "memory.search",
  "platformclaw.memory.claim.purge",
  "platformclaw.memory.claim.retire",
  "platformclaw.memory.lifecycle",
  "platformclaw.memory.get",
  "platformclaw.memory.promotion.decide",
  "platformclaw.memory.promotion.publishDirect",
  "platformclaw.memory.promotion.submit",
  "sessions.usage",
  "skills.install",
  "skills.proposals.apply",
  "skills.proposals.evaluate",
  "skills.proposals.historyScan",
  "skills.proposals.historyStatus",
  "skills.proposals.inspect",
  "skills.proposals.list",
  "skills.proposals.reject",
  "skills.proposals.requestRevision",
  "skills.securityVerdicts",
  "skills.skillCard",
  "skills.status",
  "tasks.list",
  "tools.catalog",
  "usage.cost",
]);

export const PLATFORMCLAW_WEB_ADMIN_METHODS = new Set<string>([
  "platformclaw.memory.claim.purge",
  "platformclaw.memory.promotion.publishDirect",
  "plugins.install",
  "plugins.list",
  "plugins.search",
  "plugins.setEnabled",
  "plugins.uninstall",
]);

export const PLATFORMCLAW_WEB_SESSION_KEY_METHODS = new Map<string, string>([
  ["chat.abort", "sessionKey"],
  ["chat.history", "sessionKey"],
  ["chat.message.get", "sessionKey"],
  ["chat.send", "sessionKey"],
  ["chat.startup", "sessionKey"],
  ["chat.toolTitles", "sessionKey"],
  ["artifacts.download", "sessionKey"],
  ["artifacts.list", "sessionKey"],
  ["sessions.abort", "key"],
  ["sessions.compact", "key"],
  ["sessions.describe", "key"],
  ["sessions.files.get", "sessionKey"],
  ["sessions.files.list", "sessionKey"],
  ["sessions.fork", "sessionKey"],
  ["sessions.messages.subscribe", "key"],
  ["sessions.messages.unsubscribe", "key"],
  ["sessions.patch", "key"],
  ["sessions.reset", "key"],
  ["sessions.rewind", "sessionKey"],
  ["sessions.steer", "key"],
  ["tools.effective", "sessionKey"],
]);
