/**
 * Public SDK subpath for sandbox backends, SSH execution, and temp workspace helpers.
 */
export type {
  CreateSandboxBackendParams,
  RemoteShellSandboxHandle,
  RemoteShellSandboxFilesystemRoot,
  RunSshSandboxCommandParams,
  SandboxBackendCommandParams,
  SandboxBackendCommandResult,
  SandboxBackendExecSpec,
  SandboxBackendFactory,
  SandboxFsBridge,
  SandboxFsStat,
  SandboxBackendHandle,
  SandboxBackendId,
  SandboxBackendManager,
  SandboxBackendPreparedWorkdirDiscarder,
  SandboxBackendRegistration,
  SandboxBackendRuntimeInfo,
  SandboxBackendMaterializedSkills,
  SandboxBackendReadOnlySkillMount,
  SandboxBackendSkillCatalog,
  SandboxBackendSkillFile,
  SandboxBackendSkillProvider,
  SandboxBackendSkillInstallProvider,
  SandboxBackendSkillInstallTarget,
  SandboxBackendSkillMaterializationMode,
  SandboxBackendSkillSourceMount,
  SandboxBackendSkillWorkshopProvider,
  SandboxBackendTerminalPlan,
  SandboxBackendTerminalProcess,
  SandboxBackendTerminalProvider,
  SandboxBackendWorkdirValidation,
  SandboxBackendWorkdirResolver,
  SandboxBackendWorkdirValidator,
  SandboxContext,
  SandboxResolvedPath,
  SandboxSshConfig,
  SshSandboxSession,
  SshSandboxSettings,
  SshSandboxSessionFactory,
  CreateSshSandboxBackendWithSessionFactoryOptions,
} from "../agents/sandbox.js";
export type { OpenClawConfig } from "../config/config.js";
export type {
  SkillWorkshopTargetAccess,
  SkillWorkshopTargetFile,
  SkillWorkshopTargetSkill,
} from "../skills/workshop/types.js";
export type { SkillArchiveInstallTargetAccess } from "../skills/lifecycle/archive-install.js";

export {
  buildExecRemoteCommand,
  buildRemoteWorkdirValidationCommand,
  buildRemoteCommand,
  buildSshSandboxArgv,
  buildSshLoginShellArgv,
  buildValidatedExecRemoteCommand,
  createRemoteShellSandboxFsBridge,
  createWritableRenameTargetResolver,
  createSshSandboxSessionFromConfigText,
  createSshSandboxSessionFromSettings,
  createSshSandboxBackendWithSessionFactory,
  disposeSshSandboxSession,
  getSandboxBackendFactory,
  getSandboxBackendManager,
  getSandboxBackendSkillProvider,
  getSandboxBackendSkillInstallProvider,
  getSandboxBackendSkillWorkshopProvider,
  getSandboxBackendTerminalProvider,
  getSandboxBackendWorkdirResolver,
  isToolAllowed,
  registerSandboxBackend,
  requireSandboxBackendFactory,
  resolveSandboxRuntimeStatus,
  resolveWritableRenameTargets,
  resolveWritableRenameTargetsForBridge,
  runSshSandboxCommand,
  sanitizeEnvVars,
  shellEscape,
  uploadDirectoryToSshTarget,
} from "../agents/sandbox.js";

export {
  runPluginCommandWithTimeout,
  type PluginCommandRunOptions,
  type PluginCommandRunResult,
} from "./run-command.js";
export { resolvePreferredOpenClawTmpDir } from "../infra/tmp-openclaw-dir.js";
export {
  tempWorkspace,
  tempWorkspaceSync,
  type TempWorkspace,
  type TempWorkspaceOptions,
  type TempWorkspaceSync,
  withTempWorkspace,
  withTempWorkspaceSync,
} from "../infra/private-temp-workspace.js";
